// <auto-generated />
using Smoothment.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Smoothment.Migrations
{
    [DbContext(typeof(SmoothmentDbContext))]
    partial class SmoothmentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Smoothment.Database.Category", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("SynonymousJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("Synonymous");

                    b.HasKey("Name");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Smoothment.Database.Payee", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpenseCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpenseDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("SynonymousJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("Synonymous");

                    b.Property<string>("TopUpCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("TopUpDescription")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Payees");
                });
#pragma warning restore 612, 618
        }
    }
}
